[build]
  publish = "dist"
  functions = './functions/'
  
[[redirects]]
  from = "/*"
  to = "/"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control: max-age=365000000
    Cache-Control: immutable
